"""Add first_name column to User

Revision ID: eeda241774f5
Revises: 18a3b385bd6f
Create Date: 2026-02-26 22:34:38.220166

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'eeda241774f5'
down_revision: Union[str, None] = '18a3b385bd6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('users', 'first_name')
